version: '3.8'
services:
 mysql:
  image: mysql:8
  container_name: hnf1b_mysql
  command: mysqld --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
   MYSQL_DATABASE: 'hnf1b_db'
   MYSQL_USER: 'bernt'
   MYSQL_PASSWORD: 'HNF1B-db'
   MYSQL_ROOT_PASSWORD: 'HNF1B-db'
  ports:
   - "6612:3306"
  volumes:
   - /home/bernt/hnf1b_db/data/mysql/:/var/lib/mysql/
 api:
  build: ./api/
  container_name: hnf1b_api
  command: Rscript /hnf1b_api_volume/start_hnf1b-db_api.R
  restart: always
  volumes:
  - /home/bernt/HNF1B-db/api/:/hnf1b_api_volume/
  ports:
     - "7779:7779"
  environment:
   PASSWORD: 'HNF1B-db'
 app:
  build: ./app/
  container_name: hnf1b_app
  restart: always
  ports:
     - "80:80"
volumes:
 hnf1b_api_volume: