version: '3.8'
services:
 mysql:
  image: mysql:8
  container_name: hnf1b_mysql
  command: mysqld --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
   MYSQL_DATABASE: ${MYSQL_DATABASE}
   MYSQL_USER: ${MYSQL_USER}
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  ports:
   - "6612:3306"
  volumes:
   - ../data/mysql/:/var/lib/mysql/
 api:
  build: ./api/
  container_name: hnf1b_api
  command: Rscript /hnf1b_api_volume/start_hnf1b-db_api.R
  restart: always
  volumes:
  - ./api/:/hnf1b_api_volume/
  ports:
     - "7779:7779"
  environment:
   PASSWORD: ${PASSWORD}
   SMTP_PASSWORD: ${SMTP_PASSWORD}
   API_CONFIG: ${API_CONFIG}
 app:
  build: ./app/
  container_name: hnf1b_app
  restart: always
  ports:
     - "80:80"
volumes:
 hnf1b_api_volume: