version: '3.8'
services:
 mysql:
  image: mysql:8
  container_name: hnf1b_mysql
  command: mysqld --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
   MYSQL_DATABASE: 'hnf1b_db'
   MYSQL_USER: 'bernt'
   MYSQL_PASSWORD: 'HNF1B-db'
   MYSQL_ROOT_PASSWORD: 'bepo96kamo'
  ports:
   - "6612:3306"
  volumes:
   - /home/bernt/hnf1b_db/data/mysql/:/var/lib/mysql/
