"""Add missing annotation fields to variant_annotations.

Revision ID: 0e6b4c6b60a4
Revises: ec5ac43a1a2e
Create Date: 2025-08-27 17:13:26.825745

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e6b4c6b60a4"
down_revision: Union[str, Sequence[str], None] = "ec5ac43a1a2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "variant_annotations", sa.Column("impact", sa.String(length=50), nullable=True)
    )
    op.add_column("variant_annotations", sa.Column("effect", sa.Text(), nullable=True))
    op.add_column(
        "variant_annotations",
        sa.Column("variant_class", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("variant_annotations", "variant_class")
    op.drop_column("variant_annotations", "effect")
    op.drop_column("variant_annotations", "impact")
    # ### end Alembic commands ###
