"""Remove mongodb references.

Revision ID: 1f0f2db6676a
Revises: 868cd28a1950
Create Date: 2025-08-26 17:24:29.115569

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f0f2db6676a"
down_revision: Union[str, Sequence[str], None] = "868cd28a1950"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_genes_mongo_id"), table_name="genes")
    op.drop_column("genes", "mongo_id")
    op.drop_index(op.f("ix_individuals_mongo_id"), table_name="individuals")
    op.drop_column("individuals", "mongo_id")
    op.drop_index(op.f("ix_proteins_mongo_id"), table_name="proteins")
    op.drop_column("proteins", "mongo_id")
    op.drop_index(op.f("ix_publications_mongo_id"), table_name="publications")
    op.drop_column("publications", "mongo_id")
    op.drop_index(op.f("ix_reports_mongo_id"), table_name="reports")
    op.drop_column("reports", "mongo_id")
    op.drop_index(op.f("ix_users_mongo_id"), table_name="users")
    op.drop_column("users", "mongo_id")
    op.drop_index(op.f("ix_variants_mongo_id"), table_name="variants")
    op.drop_column("variants", "mongo_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "variants",
        sa.Column(
            "mongo_id", sa.VARCHAR(length=24), autoincrement=False, nullable=True
        ),
    )
    op.create_index(op.f("ix_variants_mongo_id"), "variants", ["mongo_id"], unique=True)
    op.add_column(
        "users",
        sa.Column(
            "mongo_id", sa.VARCHAR(length=24), autoincrement=False, nullable=True
        ),
    )
    op.create_index(op.f("ix_users_mongo_id"), "users", ["mongo_id"], unique=True)
    op.add_column(
        "reports",
        sa.Column(
            "mongo_id", sa.VARCHAR(length=24), autoincrement=False, nullable=True
        ),
    )
    op.create_index(op.f("ix_reports_mongo_id"), "reports", ["mongo_id"], unique=False)
    op.add_column(
        "publications",
        sa.Column(
            "mongo_id", sa.VARCHAR(length=24), autoincrement=False, nullable=True
        ),
    )
    op.create_index(
        op.f("ix_publications_mongo_id"), "publications", ["mongo_id"], unique=True
    )
    op.add_column(
        "proteins",
        sa.Column(
            "mongo_id", sa.VARCHAR(length=24), autoincrement=False, nullable=True
        ),
    )
    op.create_index(op.f("ix_proteins_mongo_id"), "proteins", ["mongo_id"], unique=True)
    op.add_column(
        "individuals",
        sa.Column(
            "mongo_id", sa.VARCHAR(length=24), autoincrement=False, nullable=True
        ),
    )
    op.create_index(
        op.f("ix_individuals_mongo_id"), "individuals", ["mongo_id"], unique=True
    )
    op.add_column(
        "genes",
        sa.Column(
            "mongo_id", sa.VARCHAR(length=24), autoincrement=False, nullable=True
        ),
    )
    op.create_index(op.f("ix_genes_mongo_id"), "genes", ["mongo_id"], unique=True)
    # ### end Alembic commands ###
