"""Initial database schema with all tables.

Revision ID: 868cd28a1950
Revises:
Create Date: 2025-08-26 16:52:15.394737
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "868cd28a1950"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("gene_symbol", sa.String(length=50), nullable=False),
        sa.Column("ensembl_gene_id", sa.String(length=50), nullable=False),
        sa.Column("transcript", sa.String(length=50), nullable=False),
        sa.Column("exons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hg38", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hg19", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mongo_id", sa.String(length=24), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_genes")),
    )
    op.create_index(
        op.f("ix_genes_ensembl_gene_id"), "genes", ["ensembl_gene_id"], unique=True
    )
    op.create_index(
        op.f("ix_genes_gene_symbol"), "genes", ["gene_symbol"], unique=False
    )
    op.create_index(op.f("ix_genes_mongo_id"), "genes", ["mongo_id"], unique=True)
    op.create_table(
        "individuals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("individual_id", sa.String(length=20), nullable=False),
        sa.Column("sex", sa.String(length=10), nullable=True),
        sa.Column("individual_doi", sa.String(length=100), nullable=True),
        sa.Column("dup_check", sa.String(length=50), nullable=True),
        sa.Column("individual_identifier", sa.String(length=100), nullable=True),
        sa.Column("problematic", sa.String(length=500), nullable=False),
        sa.Column("mongo_id", sa.String(length=24), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_individuals")),
    )
    op.create_index(
        op.f("ix_individuals_individual_id"),
        "individuals",
        ["individual_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_individuals_mongo_id"), "individuals", ["mongo_id"], unique=True
    )
    op.create_table(
        "proteins",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("gene", sa.String(length=50), nullable=False),
        sa.Column("transcript", sa.String(length=50), nullable=False),
        sa.Column("protein", sa.String(length=50), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mongo_id", sa.String(length=24), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proteins")),
    )
    op.create_index(op.f("ix_proteins_gene"), "proteins", ["gene"], unique=False)
    op.create_index(op.f("ix_proteins_mongo_id"), "proteins", ["mongo_id"], unique=True)
    op.create_index(op.f("ix_proteins_protein"), "proteins", ["protein"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("user_role", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("family_name", sa.String(length=100), nullable=False),
        sa.Column("orcid", sa.String(length=50), nullable=True),
        sa.Column("mongo_id", sa.String(length=24), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_mongo_id"), "users", ["mongo_id"], unique=True)
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=True)
    op.create_index(op.f("ix_users_user_name"), "users", ["user_name"], unique=True)
    op.create_table(
        "variants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.String(length=20), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("mongo_id", sa.String(length=24), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_variants")),
    )
    op.create_index(
        op.f("ix_variants_is_current"), "variants", ["is_current"], unique=False
    )
    op.create_index(op.f("ix_variants_mongo_id"), "variants", ["mongo_id"], unique=True)
    op.create_index(
        op.f("ix_variants_variant_id"), "variants", ["variant_id"], unique=True
    )
    op.create_table(
        "individual_variants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("individual_id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column("detection_method", sa.String(length=100), nullable=True),
        sa.Column("segregation", sa.String(length=100), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["individual_id"],
            ["individuals.id"],
            name=op.f("fk_individual_variants_individual_id_individuals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.id"],
            name=op.f("fk_individual_variants_variant_id_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_individual_variants")),
    )
    op.create_table(
        "publications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column("publication_id", sa.String(length=20), nullable=False),
        sa.Column("publication_alias", sa.String(length=100), nullable=False),
        sa.Column("publication_type", sa.String(length=50), nullable=True),
        sa.Column("publication_entry_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pmid", sa.Integer(), nullable=True),
        sa.Column("doi", sa.String(length=200), nullable=True),
        sa.Column("pdf", sa.String(length=500), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("publication_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("journal_abbreviation", sa.String(length=100), nullable=True),
        sa.Column("journal", sa.String(length=200), nullable=True),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "medical_specialty", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("mongo_id", sa.String(length=24), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_publications_assignee_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publications")),
    )
    op.create_index(
        op.f("ix_publications_mongo_id"), "publications", ["mongo_id"], unique=True
    )
    op.create_index(
        op.f("ix_publications_pmid"), "publications", ["pmid"], unique=False
    )
    op.create_index(
        op.f("ix_publications_publication_id"),
        "publications",
        ["publication_id"],
        unique=True,
    )
    op.create_table(
        "variant_annotations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column("transcript", sa.String(length=100), nullable=True),
        sa.Column("c_dot", sa.Text(), nullable=True),
        sa.Column("p_dot", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("annotation_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.id"],
            name=op.f("fk_variant_annotations_variant_id_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_variant_annotations")),
    )
    op.create_table(
        "variant_classifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column("verdict", sa.String(length=100), nullable=True),
        sa.Column("criteria", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("system", sa.String(length=50), nullable=True),
        sa.Column("classification_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.id"],
            name=op.f("fk_variant_classifications_variant_id_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_variant_classifications")),
    )
    op.create_table(
        "authors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("lastname", sa.String(length=100), nullable=True),
        sa.Column("firstname", sa.String(length=100), nullable=True),
        sa.Column("initials", sa.String(length=20), nullable=True),
        sa.Column(
            "affiliations", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("author_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publications.id"],
            name=op.f("fk_authors_publication_id_publications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authors")),
    )
    op.create_table(
        "reported_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column("publication_ref", sa.UUID(), nullable=True),
        sa.Column("variant_reported", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["publication_ref"],
            ["publications.id"],
            name=op.f("fk_reported_entries_publication_ref_publications"),
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.id"],
            name=op.f("fk_reported_entries_variant_id_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reported_entries")),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("individual_id", sa.UUID(), nullable=False),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("publication_ref", sa.UUID(), nullable=True),
        sa.Column("report_id", sa.String(length=20), nullable=False),
        sa.Column(
            "phenotypes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("review_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("report_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("family_history", sa.Text(), nullable=True),
        sa.Column("age_reported", sa.String(length=50), nullable=True),
        sa.Column("age_onset", sa.String(length=50), nullable=True),
        sa.Column("cohort", sa.String(length=100), nullable=True),
        sa.Column("mongo_id", sa.String(length=24), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["individual_id"],
            ["individuals.id"],
            name=op.f("fk_reports_individual_id_individuals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["publication_ref"],
            ["publications.id"],
            name=op.f("fk_reports_publication_ref_publications"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_reports_reviewed_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(op.f("ix_reports_mongo_id"), "reports", ["mongo_id"], unique=False)
    op.create_index(
        op.f("ix_reports_report_id"), "reports", ["report_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reports_report_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_mongo_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_table("reported_entries")
    op.drop_table("authors")
    op.drop_table("variant_classifications")
    op.drop_table("variant_annotations")
    op.drop_index(op.f("ix_publications_publication_id"), table_name="publications")
    op.drop_index(op.f("ix_publications_pmid"), table_name="publications")
    op.drop_index(op.f("ix_publications_mongo_id"), table_name="publications")
    op.drop_table("publications")
    op.drop_table("individual_variants")
    op.drop_index(op.f("ix_variants_variant_id"), table_name="variants")
    op.drop_index(op.f("ix_variants_mongo_id"), table_name="variants")
    op.drop_index(op.f("ix_variants_is_current"), table_name="variants")
    op.drop_table("variants")
    op.drop_index(op.f("ix_users_user_name"), table_name="users")
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_mongo_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_proteins_protein"), table_name="proteins")
    op.drop_index(op.f("ix_proteins_mongo_id"), table_name="proteins")
    op.drop_index(op.f("ix_proteins_gene"), table_name="proteins")
    op.drop_table("proteins")
    op.drop_index(op.f("ix_individuals_mongo_id"), table_name="individuals")
    op.drop_index(op.f("ix_individuals_individual_id"), table_name="individuals")
    op.drop_table("individuals")
    op.drop_index(op.f("ix_genes_mongo_id"), table_name="genes")
    op.drop_index(op.f("ix_genes_gene_symbol"), table_name="genes")
    op.drop_index(op.f("ix_genes_ensembl_gene_id"), table_name="genes")
    op.drop_table("genes")
    # ### end Alembic commands ###
