"""Add genomic coordinate fields to variants table.

Revision ID: ec5ac43a1a2e
Revises: 52c26efd4c7b
Create Date: 2025-08-27 17:12:43.534304

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec5ac43a1a2e"
down_revision: Union[str, Sequence[str], None] = "52c26efd4c7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "variants", sa.Column("variant_type", sa.String(length=50), nullable=True)
    )
    op.add_column("variants", sa.Column("hg19", sa.Text(), nullable=True))
    op.add_column("variants", sa.Column("hg38", sa.Text(), nullable=True))
    op.add_column("variants", sa.Column("hg19_info", sa.Text(), nullable=True))
    op.add_column("variants", sa.Column("hg38_info", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("variants", "hg38_info")
    op.drop_column("variants", "hg19_info")
    op.drop_column("variants", "hg38")
    op.drop_column("variants", "hg19")
    op.drop_column("variants", "variant_type")
    # ### end Alembic commands ###
