# generated by datamodel-codegen:
#   filename:  openapi.snapshot.json

from __future__ import annotations

from typing import Annotated, Any, Literal, Optional, Union
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, EmailStr, Field, RootModel


class AggregationResult(BaseModel):
    count: Annotated[int, Field(title="Count")]
    details: Annotated[Optional[dict[str, Any]], Field(title="Details")] = None
    label: Annotated[str, Field(title="Label")]
    percentage: Annotated[Optional[float], Field(title="Percentage")] = None


class AuthorModel(BaseModel):
    affiliation: Annotated[Optional[str], Field(title="Affiliation")] = None
    name: Annotated[str, Field(title="Name")]


class BatchRecodeRequest(BaseModel):
    include_vcf: Annotated[Optional[bool], Field(title="Include Vcf")] = True
    variants: Annotated[list[str], Field(title="Variants")]


class BatchRecodeResponse(BaseModel):
    failed_count: Annotated[int, Field(title="Failed Count")]
    results: Annotated[dict[str, Optional[dict[str, Any]]], Field(title="Results")]
    success_count: Annotated[int, Field(title="Success Count")]


class CommentCreate(BaseModel):
    body_markdown: Annotated[
        str, Field(max_length=10000, min_length=1, title="Body Markdown")
    ]
    mention_user_ids: Annotated[
        Optional[list[int]], Field(max_length=50, title="Mention User Ids")
    ] = None
    record_id: Annotated[UUID, Field(title="Record Id")]
    record_type: Annotated[Literal["phenopacket"], Field(title="Record Type")]


class CommentEditResponse(BaseModel):
    edited_at: Annotated[AwareDatetime, Field(title="Edited At")]
    editor_id: Annotated[int, Field(title="Editor Id")]
    editor_username: Annotated[str, Field(title="Editor Username")]
    id: Annotated[int, Field(title="Id")]
    prev_body: Annotated[str, Field(title="Prev Body")]


class CommentMentionOut(BaseModel):
    display_name: Annotated[Optional[str], Field(title="Display Name")] = None
    is_active: Annotated[bool, Field(title="Is Active")]
    user_id: Annotated[int, Field(title="User Id")]
    username: Annotated[str, Field(title="Username")]


class CommentResponse(BaseModel):
    author_display_name: Annotated[
        Optional[str], Field(title="Author Display Name")
    ] = None
    author_id: Annotated[int, Field(title="Author Id")]
    author_username: Annotated[str, Field(title="Author Username")]
    body_markdown: Annotated[str, Field(title="Body Markdown")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    deleted_at: Annotated[Optional[AwareDatetime], Field(title="Deleted At")] = None
    deleted_by_id: Annotated[Optional[int], Field(title="Deleted By Id")] = None
    edited: Annotated[Optional[bool], Field(title="Edited")] = False
    id: Annotated[int, Field(title="Id")]
    mentions: Annotated[Optional[list[CommentMentionOut]], Field(title="Mentions")] = (
        None
    )
    record_id: Annotated[str, Field(title="Record Id")]
    record_type: Annotated[str, Field(title="Record Type")]
    resolved_at: Annotated[Optional[AwareDatetime], Field(title="Resolved At")] = None
    resolved_by_id: Annotated[Optional[int], Field(title="Resolved By Id")] = None
    resolved_by_username: Annotated[
        Optional[str], Field(title="Resolved By Username")
    ] = None
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class CommentUpdate(BaseModel):
    body_markdown: Annotated[
        str, Field(max_length=10000, min_length=1, title="Body Markdown")
    ]
    mention_user_ids: Annotated[
        Optional[list[int]], Field(max_length=50, title="Mention User Ids")
    ] = None


class CursorLinksObject(BaseModel):
    first: Annotated[str, Field(title="First")]
    next: Annotated[Optional[str], Field(title="Next")] = None
    prev: Annotated[Optional[str], Field(title="Prev")] = None
    self: Annotated[str, Field(title="Self")]


class Total(RootModel[int]):
    root: Annotated[
        int, Field(description="Total records matching filters", ge=0, title="Total")
    ]


class CursorPageMeta(BaseModel):
    endCursor: Annotated[Optional[str], Field(title="Endcursor")] = None
    hasNextPage: Annotated[bool, Field(title="Hasnextpage")]
    hasPreviousPage: Annotated[bool, Field(title="Haspreviouspage")]
    pageSize: Annotated[int, Field(ge=1, le=1000, title="Pagesize")]
    startCursor: Annotated[Optional[str], Field(title="Startcursor")] = None
    total: Annotated[
        Optional[Total],
        Field(description="Total records matching filters", title="Total"),
    ] = None


class DataSyncStatus(BaseModel):
    last_sync: Annotated[
        Optional[str], Field(description="Last sync timestamp", title="Last Sync")
    ] = None
    name: Annotated[str, Field(description="Name of the data category", title="Name")]
    pending: Annotated[int, Field(description="Items pending sync", title="Pending")]
    synced: Annotated[
        int, Field(description="Items with complete metadata", title="Synced")
    ]
    total: Annotated[int, Field(description="Total items in database", title="Total")]


class ExonSchema(BaseModel):
    chromosome: Annotated[str, Field(description="Chromosome", title="Chromosome")]
    end: Annotated[
        int, Field(description="Exon end position (genomic, 1-based)", title="End")
    ]
    exon_number: Annotated[
        int, Field(description="Exon number (1-based)", title="Exon Number")
    ]
    extra_data: Annotated[Optional[dict[str, Any]], Field(title="Extra Data")] = None
    id: Annotated[UUID, Field(title="Id")]
    phase: Annotated[
        Optional[int],
        Field(description="Reading frame phase (0, 1, or 2)", title="Phase"),
    ] = None
    source: Annotated[str, Field(description="Data source", title="Source")]
    start: Annotated[
        int, Field(description="Exon start position (genomic, 1-based)", title="Start")
    ]
    strand: Annotated[str, Field(description="DNA strand ('+' or '-')", title="Strand")]


class GeneSchema(BaseModel):
    chromosome: Annotated[str, Field(description="Chromosome", title="Chromosome")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    end: Annotated[
        int, Field(description="Genomic end position (1-based)", title="End")
    ]
    ensembl_id: Annotated[
        Optional[str], Field(description="Ensembl gene ID", title="Ensembl Id")
    ] = None
    extra_data: Annotated[Optional[dict[str, Any]], Field(title="Extra Data")] = None
    hgnc_id: Annotated[Optional[str], Field(description="HGNC ID", title="Hgnc Id")] = (
        None
    )
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(description="Full gene name", title="Name")]
    ncbi_gene_id: Annotated[
        Optional[str], Field(description="NCBI Gene ID", title="Ncbi Gene Id")
    ] = None
    omim_id: Annotated[Optional[str], Field(description="OMIM ID", title="Omim Id")] = (
        None
    )
    source: Annotated[str, Field(description="Data source", title="Source")]
    source_url: Annotated[
        Optional[str], Field(description="URL to source record", title="Source Url")
    ] = None
    source_version: Annotated[
        Optional[str],
        Field(description="Source database version", title="Source Version"),
    ] = None
    start: Annotated[
        int, Field(description="Genomic start position (1-based)", title="Start")
    ]
    strand: Annotated[str, Field(description="DNA strand ('+' or '-')", title="Strand")]
    symbol: Annotated[str, Field(description="Gene symbol", title="Symbol")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class GenomicRegionResponse(BaseModel):
    genes: Annotated[
        Optional[list[GeneSchema]], Field(description="Genes in region", title="Genes")
    ] = None
    genome_build: Annotated[
        str, Field(description="Genome assembly", title="Genome Build")
    ]
    region: Annotated[
        str, Field(description="Genomic region (chr:start-end)", title="Region")
    ]
    total: Annotated[int, Field(description="Total number of genes", title="Total")]


class FullName(RootModel[str]):
    root: Annotated[str, Field(max_length=255, title="Full Name")]


class InviteAcceptRequest(BaseModel):
    full_name: Annotated[Optional[FullName], Field(title="Full Name")] = None
    password: Annotated[str, Field(min_length=8, title="Password")]
    username: Annotated[str, Field(max_length=50, min_length=3, title="Username")]


class InviteRequest(BaseModel):
    email: Annotated[EmailStr, Field(title="Email")]
    role: Annotated[
        Optional[str], Field(pattern="^(admin|curator|viewer)$", title="Role")
    ] = "viewer"


class InviteResponse(BaseModel):
    email: Annotated[str, Field(title="Email")]
    expires_at: Annotated[AwareDatetime, Field(title="Expires At")]
    role: Annotated[str, Field(title="Role")]
    token: Annotated[Optional[str], Field(title="Token")] = None


class LinksObject(BaseModel):
    first: Annotated[str, Field(title="First")]
    last: Annotated[str, Field(title="Last")]
    next: Annotated[Optional[str], Field(title="Next")] = None
    prev: Annotated[Optional[str], Field(title="Prev")] = None
    self: Annotated[str, Field(title="Self")]


class MentionableUserOut(BaseModel):
    display_name: Annotated[Optional[str], Field(title="Display Name")] = None
    id: Annotated[int, Field(title="Id")]
    username: Annotated[str, Field(title="Username")]


class MessageResponse(BaseModel):
    message: Annotated[str, Field(title="Message")]
    token: Annotated[Optional[str], Field(title="Token")] = None


class MolecularConsequence(
    RootModel[
        Literal[
            "Frameshift",
            "Nonsense",
            "Missense",
            "Splice Donor",
            "Splice Acceptor",
            "In-frame Deletion",
            "In-frame Insertion",
            "Synonymous",
            "Intronic Variant",
            "Coding Sequence Variant",
        ]
    ]
):
    root: Annotated[
        Literal[
            "Frameshift",
            "Nonsense",
            "Missense",
            "Splice Donor",
            "Splice Acceptor",
            "In-frame Deletion",
            "In-frame Insertion",
            "Synonymous",
            "Intronic Variant",
            "Coding Sequence Variant",
        ],
        Field(
            description="Molecular consequence of a variant, computed from HGVS notation.\n\nCNV-related consequences (copy-number loss/gain) are intentionally omitted\nbecause they are covered by the :class:`VariantType` filter instead.",
            title="MolecularConsequence",
        ),
    ]


class PageMeta(BaseModel):
    currentPage: Annotated[int, Field(ge=1, title="Currentpage")]
    pageSize: Annotated[int, Field(ge=1, le=1000, title="Pagesize")]
    totalPages: Annotated[int, Field(ge=0, title="Totalpages")]
    totalRecords: Annotated[int, Field(ge=0, title="Totalrecords")]


class PasswordChange(BaseModel):
    current_password: Annotated[str, Field(title="Current Password")]
    new_password: Annotated[str, Field(min_length=8, title="New Password")]


class PasswordResetConfirm(BaseModel):
    new_password: Annotated[str, Field(min_length=8, title="New Password")]


class PasswordResetRequest(BaseModel):
    email: Annotated[EmailStr, Field(title="Email")]


class PhenopacketAuditResponse(BaseModel):
    action: Annotated[str, Field(title="Action")]
    change_patch: Annotated[Any, Field(title="Change Patch")] = None
    change_reason: Annotated[Optional[str], Field(title="Change Reason")] = None
    change_summary: Annotated[Optional[str], Field(title="Change Summary")] = None
    changed_at: Annotated[AwareDatetime, Field(title="Changed At")]
    changed_by: Annotated[Optional[str], Field(title="Changed By")] = None
    id: Annotated[str, Field(title="Id")]
    new_value: Annotated[Optional[dict[str, Any]], Field(title="New Value")] = None
    old_value: Annotated[Optional[dict[str, Any]], Field(title="Old Value")] = None
    phenopacket_id: Annotated[str, Field(title="Phenopacket Id")]
    source: Annotated[Optional[str], Field(title="Source")] = "audit"
    state_transition: Annotated[
        Optional[dict[str, Optional[str]]], Field(title="State Transition")
    ] = None


class PhenopacketCreate(BaseModel):
    phenopacket: Annotated[dict[str, Any], Field(title="Phenopacket")]


class PhenopacketDelete(BaseModel):
    change_reason: Annotated[
        str,
        Field(
            description="Reason for deletion (audit trail)",
            min_length=1,
            title="Change Reason",
        ),
    ]
    revision: Annotated[
        int,
        Field(
            description="Required optimistic-locking revision. Delete returns 409 Conflict when the current row revision differs.",
            title="Revision",
        ),
    ]


class PhenopacketResponse(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    created_by: Annotated[Optional[str], Field(title="Created By")] = None
    draft_owner_id: Annotated[Optional[int], Field(title="Draft Owner Id")] = None
    draft_owner_username: Annotated[
        Optional[str], Field(title="Draft Owner Username")
    ] = None
    editing_revision_id: Annotated[
        Optional[int], Field(title="Editing Revision Id")
    ] = None
    effective_state: Annotated[Optional[str], Field(title="Effective State")] = None
    head_published_revision_id: Annotated[
        Optional[int], Field(title="Head Published Revision Id")
    ] = None
    id: Annotated[str, Field(title="Id")]
    phenopacket: Annotated[dict[str, Any], Field(title="Phenopacket")]
    phenopacket_id: Annotated[str, Field(title="Phenopacket Id")]
    revision: Annotated[int, Field(title="Revision")]
    schema_version: Annotated[str, Field(title="Schema Version")]
    state: Annotated[Optional[str], Field(title="State")] = "draft"
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    updated_by: Annotated[Optional[str], Field(title="Updated By")] = None
    version: Annotated[str, Field(title="Version")]


class PhenopacketUpdate(BaseModel):
    change_reason: Annotated[
        str,
        Field(
            description="Reason for the change (audit trail)",
            min_length=1,
            title="Change Reason",
        ),
    ]
    phenopacket: Annotated[dict[str, Any], Field(title="Phenopacket")]
    revision: Annotated[
        Optional[int],
        Field(
            description="Optional revision for optimistic locking (disabled if not provided)",
            title="Revision",
        ),
    ] = None


class PhenotypeComparison(BaseModel):
    effect_size: Annotated[
        Optional[float],
        Field(
            description="Effect size (Cohen's h for proportions)", title="Effect Size"
        ),
    ] = None
    group1_absent: Annotated[
        int, Field(description="Count absent in group 1", title="Group1 Absent")
    ]
    group1_percentage: Annotated[
        float,
        Field(description="Percentage present in group 1", title="Group1 Percentage"),
    ]
    group1_present: Annotated[
        int, Field(description="Count present in group 1", title="Group1 Present")
    ]
    group1_total: Annotated[
        int, Field(description="Total individuals in group 1", title="Group1 Total")
    ]
    group2_absent: Annotated[
        int, Field(description="Count absent in group 2", title="Group2 Absent")
    ]
    group2_percentage: Annotated[
        float,
        Field(description="Percentage present in group 2", title="Group2 Percentage"),
    ]
    group2_present: Annotated[
        int, Field(description="Count present in group 2", title="Group2 Present")
    ]
    group2_total: Annotated[
        int, Field(description="Total individuals in group 2", title="Group2 Total")
    ]
    hpo_id: Annotated[str, Field(description="HPO term identifier", title="Hpo Id")]
    hpo_label: Annotated[
        str, Field(description="Human-readable phenotype name", title="Hpo Label")
    ]
    odds_ratio: Annotated[
        Optional[float],
        Field(description="Odds ratio from Fisher's exact test", title="Odds Ratio"),
    ] = None
    p_value: Annotated[
        Optional[float],
        Field(description="Raw p-value from Fisher's exact test", title="P Value"),
    ] = None
    p_value_fdr: Annotated[
        Optional[float],
        Field(
            description="FDR-adjusted p-value (Benjamini-Hochberg correction)",
            title="P Value Fdr",
        ),
    ] = None
    significant: Annotated[
        bool,
        Field(
            description="Whether difference is statistically significant (FDR < 0.05)",
            title="Significant",
        ),
    ]
    test_used: Annotated[
        Optional[str],
        Field(description="Statistical test used (fisher_exact)", title="Test Used"),
    ] = None


class ProteinDomain(
    RootModel[
        Literal[
            "Dimerization Domain",
            "POU-Specific Domain",
            "POU Homeodomain",
            "Transactivation Domain",
        ]
    ]
):
    root: Annotated[
        Literal[
            "Dimerization Domain",
            "POU-Specific Domain",
            "POU Homeodomain",
            "Transactivation Domain",
        ],
        Field(
            description="HNF1B protein domains (UniProt P35680) used for domain-based filtering.\n\nEach member corresponds to an amino-acid range; the canonical ranges live in\n``DOMAIN_BOUNDARIES`` in the all-variants aggregation router, keyed by these\nmember values.",
            title="ProteinDomain",
        ),
    ]


class ProteinDomainSchema(BaseModel):
    end: Annotated[
        int, Field(description="Domain end position (amino acid, 1-based)", title="End")
    ]
    evidence_code: Annotated[
        Optional[str], Field(description="Evidence code", title="Evidence Code")
    ] = None
    extra_data: Annotated[Optional[dict[str, Any]], Field(title="Extra Data")] = None
    function: Annotated[
        Optional[str],
        Field(description="Domain function description", title="Function"),
    ] = None
    id: Annotated[UUID, Field(title="Id")]
    interpro_id: Annotated[
        Optional[str], Field(description="InterPro identifier", title="Interpro Id")
    ] = None
    length: Annotated[
        int, Field(description="Domain length (amino acids)", title="Length")
    ]
    name: Annotated[str, Field(description="Domain name", title="Name")]
    pfam_id: Annotated[
        Optional[str], Field(description="Pfam identifier", title="Pfam Id")
    ] = None
    short_name: Annotated[
        Optional[str], Field(description="Short domain name", title="Short Name")
    ] = None
    source: Annotated[str, Field(description="Data source", title="Source")]
    source_url: Annotated[
        Optional[str], Field(description="URL to domain annotation", title="Source Url")
    ] = None
    start: Annotated[
        int,
        Field(description="Domain start position (amino acid, 1-based)", title="Start"),
    ]
    uniprot_id: Annotated[
        Optional[str], Field(description="UniProt accession", title="Uniprot Id")
    ] = None


class ProteinDomainsResponse(BaseModel):
    domains: Annotated[
        Optional[list[ProteinDomainSchema]],
        Field(description="Protein domains", title="Domains"),
    ] = None
    gene: Annotated[str, Field(description="Gene symbol", title="Gene")]
    genome_build: Annotated[
        str, Field(description="Genome assembly", title="Genome Build")
    ]
    length: Annotated[
        Optional[int], Field(description="Protein length (amino acids)", title="Length")
    ] = None
    protein: Annotated[
        Optional[str], Field(description="RefSeq protein ID", title="Protein")
    ] = None
    uniprot: Annotated[
        Optional[str], Field(description="UniProt accession", title="Uniprot")
    ] = None
    updated_at: Annotated[
        Optional[AwareDatetime],
        Field(
            description="Last update timestamp (None if data unavailable)",
            title="Updated At",
        ),
    ] = None


class PublicationMetadataResponse(BaseModel):
    abstract: Annotated[
        Optional[str],
        Field(description="Abstract text (may be null)", title="Abstract"),
    ] = None
    authors: Annotated[
        list[AuthorModel],
        Field(description="List of authors with affiliations", title="Authors"),
    ]
    data_source: Annotated[
        Optional[str], Field(description="Data source", title="Data Source")
    ] = "PubMed"
    doi: Annotated[Optional[str], Field(description="DOI identifier", title="Doi")] = (
        None
    )
    fetched_at: Annotated[
        str, Field(description="Storage timestamp", title="Fetched At")
    ]
    journal: Annotated[
        Optional[str], Field(description="Journal name", title="Journal")
    ] = None
    pmid: Annotated[
        str, Field(description="PubMed ID in format PMID:12345678", title="Pmid")
    ]
    title: Annotated[str, Field(description="Publication title", title="Title")]
    year: Annotated[
        Optional[int], Field(description="Publication year", title="Year")
    ] = None


class ReferenceGenomeSchema(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    ensembl_name: Annotated[
        Optional[str], Field(description="Ensembl assembly name", title="Ensembl Name")
    ] = None
    extra_data: Annotated[
        Optional[dict[str, Any]],
        Field(description="Additional extra_data", title="Extra Data"),
    ] = None
    id: Annotated[UUID, Field(title="Id")]
    is_default: Annotated[
        bool,
        Field(description="Whether this is the default assembly", title="Is Default"),
    ]
    name: Annotated[
        str, Field(description="Assembly name (e.g., 'GRCh38', 'hg38')", title="Name")
    ]
    ncbi_name: Annotated[
        Optional[str], Field(description="NCBI assembly accession", title="Ncbi Name")
    ] = None
    release_date: Annotated[
        Optional[AwareDatetime],
        Field(description="Official release date", title="Release Date"),
    ] = None
    source_url: Annotated[
        Optional[str],
        Field(description="URL to assembly information", title="Source Url"),
    ] = None
    ucsc_name: Annotated[
        Optional[str], Field(description="UCSC genome browser name", title="Ucsc Name")
    ] = None
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    version: Annotated[
        Optional[str], Field(description="Assembly version/patch", title="Version")
    ] = None


class RoleResponse(BaseModel):
    description: Annotated[str, Field(title="Description")]
    permissions: Annotated[list[str], Field(title="Permissions")]
    role: Annotated[str, Field(title="Role")]


class SearchResultItem(BaseModel):
    extra_info: Annotated[
        Optional[str], Field(description="Additional context info", title="Extra Info")
    ] = None
    id: Annotated[str, Field(description="Unique identifier", title="Id")]
    label: Annotated[str, Field(description="Display label", title="Label")]
    score: Annotated[
        Optional[float], Field(description="Search relevance score", title="Score")
    ] = None
    subtype: Annotated[
        Optional[str], Field(description="Entity subtype", title="Subtype")
    ] = None
    type: Annotated[
        str,
        Field(
            description="Entity type (Gene, Variant, Phenopacket, etc.)", title="Type"
        ),
    ]


class SyncProgressResponse(BaseModel):
    completed_at: Annotated[
        Optional[str], Field(description="Task completion time", title="Completed At")
    ] = None
    errors: Annotated[
        Optional[int], Field(description="Number of errors", title="Errors")
    ] = 0
    processed: Annotated[int, Field(description="Items processed", title="Processed")]
    progress: Annotated[
        float, Field(description="Progress percentage (0-100)", title="Progress")
    ]
    started_at: Annotated[
        Optional[str], Field(description="Task start time", title="Started At")
    ] = None
    status: Annotated[
        str,
        Field(
            description="Task status (pending/running/completed/failed)", title="Status"
        ),
    ]
    task_id: Annotated[str, Field(description="Task identifier", title="Task Id")]
    total: Annotated[int, Field(description="Total items", title="Total")]


class SyncResponse(BaseModel):
    already_stored: Annotated[
        Optional[int], Field(description="PMIDs already stored", title="Already Stored")
    ] = None
    message: Annotated[
        str, Field(description="Human-readable message", title="Message")
    ]
    status: Annotated[str, Field(description="Status of the operation", title="Status")]
    to_fetch: Annotated[
        Optional[int], Field(description="PMIDs to fetch from PubMed", title="To Fetch")
    ] = None
    total_pmids: Annotated[
        Optional[int], Field(description="Total PMIDs to sync", title="Total Pmids")
    ] = None


class SyncTaskResponse(BaseModel):
    estimated_time_seconds: Annotated[
        Optional[int],
        Field(description="Estimated time to complete", title="Estimated Time Seconds"),
    ] = None
    items_to_process: Annotated[
        int, Field(description="Number of items to process", title="Items To Process")
    ]
    message: Annotated[
        str, Field(description="Human-readable message", title="Message")
    ]
    status: Annotated[str, Field(description="Task status", title="Status")]
    task_id: Annotated[
        str, Field(description="Unique task identifier", title="Task Id")
    ]


class SystemStatusResponse(BaseModel):
    database: Annotated[
        dict[str, Any], Field(description="Database statistics", title="Database")
    ]
    status: Annotated[
        Optional[str], Field(description="Overall system status", title="Status")
    ] = "healthy"
    sync_status: Annotated[
        list[DataSyncStatus],
        Field(
            description="Status of various data sync operations", title="Sync Status"
        ),
    ]
    timestamp: Annotated[
        str, Field(description="Current server timestamp", title="Timestamp")
    ]


class Token(BaseModel):
    access_token: Annotated[str, Field(title="Access Token")]
    expires_in: Annotated[int, Field(title="Expires In")]
    refresh_token: Annotated[Optional[str], Field(title="Refresh Token")] = None
    token_type: Annotated[Optional[str], Field(title="Token Type")] = "bearer"


class TranscriptDetailSchema(BaseModel):
    cds_end: Annotated[
        Optional[int], Field(description="CDS end position (genomic)", title="Cds End")
    ] = None
    cds_start: Annotated[
        Optional[int],
        Field(description="CDS start position (genomic)", title="Cds Start"),
    ] = None
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    exon_count: Annotated[int, Field(description="Number of exons", title="Exon Count")]
    exons: Annotated[
        Optional[list[ExonSchema]], Field(description="Exon list", title="Exons")
    ] = None
    extra_data: Annotated[Optional[dict[str, Any]], Field(title="Extra Data")] = None
    id: Annotated[UUID, Field(title="Id")]
    is_canonical: Annotated[
        bool,
        Field(
            description="Whether this is the canonical transcript", title="Is Canonical"
        ),
    ]
    protein_id: Annotated[
        Optional[str], Field(description="RefSeq protein ID", title="Protein Id")
    ] = None
    source: Annotated[str, Field(description="Data source", title="Source")]
    source_url: Annotated[
        Optional[str], Field(description="URL to transcript record", title="Source Url")
    ] = None
    transcript_id: Annotated[
        str, Field(description="RefSeq or Ensembl transcript ID", title="Transcript Id")
    ]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class TranscriptSchema(BaseModel):
    cds_end: Annotated[
        Optional[int], Field(description="CDS end position (genomic)", title="Cds End")
    ] = None
    cds_start: Annotated[
        Optional[int],
        Field(description="CDS start position (genomic)", title="Cds Start"),
    ] = None
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    exon_count: Annotated[int, Field(description="Number of exons", title="Exon Count")]
    extra_data: Annotated[Optional[dict[str, Any]], Field(title="Extra Data")] = None
    id: Annotated[UUID, Field(title="Id")]
    is_canonical: Annotated[
        bool,
        Field(
            description="Whether this is the canonical transcript", title="Is Canonical"
        ),
    ]
    protein_id: Annotated[
        Optional[str], Field(description="RefSeq protein ID", title="Protein Id")
    ] = None
    source: Annotated[str, Field(description="Data source", title="Source")]
    source_url: Annotated[
        Optional[str], Field(description="URL to transcript record", title="Source Url")
    ] = None
    transcript_id: Annotated[
        str, Field(description="RefSeq or Ensembl transcript ID", title="Transcript Id")
    ]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class TransitionRequest(BaseModel):
    reason: Annotated[str, Field(max_length=500, min_length=1, title="Reason")]
    revision: Annotated[int, Field(title="Revision")]
    to_state: Annotated[
        Literal[
            "draft",
            "in_review",
            "changes_requested",
            "approved",
            "published",
            "archived",
        ],
        Field(title="To State"),
    ]


class UserCreate(BaseModel):
    email: Annotated[EmailStr, Field(title="Email")]
    full_name: Annotated[Optional[FullName], Field(title="Full Name")] = None
    password: Annotated[str, Field(min_length=8, title="Password")]
    role: Annotated[
        Optional[str], Field(pattern="^(admin|curator|viewer)$", title="Role")
    ] = "viewer"
    username: Annotated[str, Field(max_length=50, min_length=3, title="Username")]


class UserLogin(BaseModel):
    password: Annotated[str, Field(min_length=8, title="Password")]
    username: Annotated[str, Field(max_length=50, min_length=3, title="Username")]


class UserResponse(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    email: Annotated[str, Field(title="Email")]
    full_name: Annotated[Optional[str], Field(title="Full Name")] = None
    id: Annotated[int, Field(title="Id")]
    is_active: Annotated[bool, Field(title="Is Active")]
    is_verified: Annotated[bool, Field(title="Is Verified")]
    last_login: Annotated[Optional[AwareDatetime], Field(title="Last Login")] = None
    permissions: Annotated[list[str], Field(title="Permissions")]
    role: Annotated[str, Field(title="Role")]
    updated_at: Annotated[Optional[AwareDatetime], Field(title="Updated At")] = None
    username: Annotated[str, Field(title="Username")]


class Password(RootModel[str]):
    root: Annotated[str, Field(min_length=8, title="Password")]


class Role(RootModel[str]):
    root: Annotated[str, Field(pattern="^(admin|curator|viewer)$", title="Role")]


class UserUpdateAdmin(BaseModel):
    email: Annotated[Optional[EmailStr], Field(title="Email")] = None
    full_name: Annotated[Optional[FullName], Field(title="Full Name")] = None
    is_active: Annotated[Optional[bool], Field(title="Is Active")] = None
    password: Annotated[Optional[Password], Field(title="Password")] = None
    role: Annotated[Optional[Role], Field(title="Role")] = None


class ValidationError(BaseModel):
    ctx: Annotated[Optional[dict[str, Any]], Field(title="Context")] = None
    input: Annotated[Optional[Any], Field(title="Input")] = None
    loc: Annotated[list[Union[str, int]], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]


class VariantClassification(
    RootModel[
        Literal[
            "PATHOGENIC",
            "LIKELY_PATHOGENIC",
            "UNCERTAIN_SIGNIFICANCE",
            "LIKELY_BENIGN",
            "BENIGN",
        ]
    ]
):
    root: Annotated[
        Literal[
            "PATHOGENIC",
            "LIKELY_PATHOGENIC",
            "UNCERTAIN_SIGNIFICANCE",
            "LIKELY_BENIGN",
            "BENIGN",
        ],
        Field(
            description="ACMG/AMP pathogenicity classification of a variant.\n\nMember values match the classifications stored on phenopacket\ninterpretations and exposed through the variant search filters.",
            title="VariantClassification",
        ),
    ]


class VariantType(
    RootModel[
        Literal[
            "SNV", "deletion", "duplication", "insertion", "indel", "inversion", "CNV"
        ]
    ]
):
    root: Annotated[
        Literal[
            "SNV", "deletion", "duplication", "insertion", "indel", "inversion", "CNV"
        ],
        Field(
            description="Structural type of a variant.\n\nMirrors the GA4GH/VRS-style structural type values stored on variation\ndescriptors in the phenopacket data.",
            title="VariantType",
        ),
    ]


class VariantValidationRequest(BaseModel):
    notation: Annotated[str, Field(title="Notation")]
    notation_type: Annotated[Optional[str], Field(title="Notation Type")] = None


class VariantValidationResponse(BaseModel):
    errors: Annotated[list[str], Field(title="Errors")]
    is_valid: Annotated[bool, Field(title="Is Valid")]
    notation: Annotated[str, Field(title="Notation")]
    notation_type: Annotated[Optional[str], Field(title="Notation Type")] = None
    standardized_formats: Annotated[
        Optional[dict[str, Any]], Field(title="Standardized Formats")
    ] = None
    suggestions: Annotated[list[str], Field(title="Suggestions")]
    vep_annotation: Annotated[
        Optional[dict[str, Any]], Field(title="Vep Annotation")
    ] = None


class AutocompleteResponse(BaseModel):
    results: Annotated[Optional[list[SearchResultItem]], Field(title="Results")] = None


class ComparisonResult(BaseModel):
    group1_count: Annotated[
        int, Field(description="Total individuals in group 1", title="Group1 Count")
    ]
    group1_name: Annotated[
        str, Field(description="Name of first group", title="Group1 Name")
    ]
    group2_count: Annotated[
        int, Field(description="Total individuals in group 2", title="Group2 Count")
    ]
    group2_name: Annotated[
        str, Field(description="Name of second group", title="Group2 Name")
    ]
    metadata: Annotated[
        Optional[dict[str, Any]],
        Field(description="Additional metadata", title="Metadata"),
    ] = None
    phenotypes: Annotated[
        list[PhenotypeComparison],
        Field(description="List of phenotype comparisons", title="Phenotypes"),
    ]


class CursorMetaObject(BaseModel):
    page: CursorPageMeta


class GeneDetailSchema(BaseModel):
    chromosome: Annotated[str, Field(description="Chromosome", title="Chromosome")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    end: Annotated[
        int, Field(description="Genomic end position (1-based)", title="End")
    ]
    ensembl_id: Annotated[
        Optional[str], Field(description="Ensembl gene ID", title="Ensembl Id")
    ] = None
    extra_data: Annotated[Optional[dict[str, Any]], Field(title="Extra Data")] = None
    hgnc_id: Annotated[Optional[str], Field(description="HGNC ID", title="Hgnc Id")] = (
        None
    )
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(description="Full gene name", title="Name")]
    ncbi_gene_id: Annotated[
        Optional[str], Field(description="NCBI Gene ID", title="Ncbi Gene Id")
    ] = None
    omim_id: Annotated[Optional[str], Field(description="OMIM ID", title="Omim Id")] = (
        None
    )
    source: Annotated[str, Field(description="Data source", title="Source")]
    source_url: Annotated[
        Optional[str], Field(description="URL to source record", title="Source Url")
    ] = None
    source_version: Annotated[
        Optional[str],
        Field(description="Source database version", title="Source Version"),
    ] = None
    start: Annotated[
        int, Field(description="Genomic start position (1-based)", title="Start")
    ]
    strand: Annotated[str, Field(description="DNA strand ('+' or '-')", title="Strand")]
    symbol: Annotated[str, Field(description="Gene symbol", title="Symbol")]
    transcripts: Annotated[
        Optional[list[TranscriptSchema]],
        Field(description="Transcript isoforms", title="Transcripts"),
    ] = None
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class GlobalSearchResponse(BaseModel):
    page: Annotated[
        Optional[int], Field(description="Current page number", title="Page")
    ] = 1
    page_size: Annotated[
        Optional[int], Field(description="Results per page", title="Page Size")
    ] = 20
    results: Annotated[Optional[list[SearchResultItem]], Field(title="Results")] = None
    summary: Annotated[
        Optional[dict[str, int]],
        Field(description="Result counts grouped by type", title="Summary"),
    ] = None
    total: Annotated[
        int, Field(description="Total matching results across all types", title="Total")
    ]


class HTTPValidationError(BaseModel):
    detail: Annotated[Optional[list[ValidationError]], Field(title="Detail")] = None


class JsonApiCursorResponse(BaseModel):
    data: Annotated[list[Any], Field(title="Data")]
    links: CursorLinksObject
    meta: CursorMetaObject


class MetaObject(BaseModel):
    page: PageMeta


class JsonApiResponse(BaseModel):
    data: Annotated[list[Any], Field(title="Data")]
    links: LinksObject
    meta: MetaObject
