"""add refresh session persistence

Revision ID: 20260415_0005
Revises: 483990d7e28f
Create Date: 2026-04-15
"""

from typing import Sequence, Union

from alembic import op

revision: str = "20260415_0005"
down_revision: Union[str, Sequence[str], None] = "483990d7e28f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add refresh-session persistence and per-user session versioning."""
    op.execute(
        """
        ALTER TABLE users
        ADD COLUMN session_version INTEGER NOT NULL DEFAULT 1;
        """
    )
    op.execute(
        """
        CREATE TABLE refresh_sessions (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          token_jti VARCHAR(64) NOT NULL UNIQUE,
          token_sha256 VARCHAR(64) NOT NULL UNIQUE,
          session_version BIGINT NOT NULL,
          expires_at TIMESTAMPTZ NOT NULL,
          revoked_at TIMESTAMPTZ NULL,
          rotated_from_jti VARCHAR(64) NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );
        """
    )
    op.execute(
        """
        CREATE INDEX ix_refresh_sessions_user_id ON refresh_sessions (user_id);
        """
    )
    op.execute(
        """
        CREATE INDEX ix_refresh_sessions_rotated_from_jti
        ON refresh_sessions (rotated_from_jti);
        """
    )


def downgrade() -> None:
    """Remove refresh-session persistence and per-user session versioning."""
    op.execute("DROP TABLE IF EXISTS refresh_sessions;")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS session_version;")
