"""fk audit actor columns

Revision ID: 7ddc07dd9e1c
Revises: dfc94a9994c9
Create Date: 2026-04-11 15:24:57.700171

Wave 5a Task 3: FK-ify the four audit-actor columns so they reference
``users.id`` instead of storing a free-form username string. This
tightens referential integrity and lets the API resolve usernames
through a relationship instead of trusting whatever string happened to
be written at insert time.

Columns touched:

- ``phenopackets.created_by``    → ``created_by_id`` (BIGINT FK)
- ``phenopackets.updated_by``    → ``updated_by_id`` (BIGINT FK)
- ``phenopackets.deleted_by``    → ``deleted_by_id`` (BIGINT FK)
- ``phenopacket_audit.changed_by`` → ``changed_by_id`` (BIGINT FK)

Migration strategy (data-preserving):

1. Seed a ``_system_migration_`` placeholder user
   (``is_active=FALSE``, ``is_fixture_user=FALSE``) so rows with
   unmapped usernames have a valid FK target. The placeholder is never
   logged into because its bcrypt hash is not a real password.
2. Add each new ``*_id`` column as nullable BIGINT.
3. Populate each new column by JOINing the existing string value
   against ``users.username``.
4. Fall back any remaining non-null old values to the placeholder id.
5. Add ``ON DELETE SET NULL`` FK constraints.
6. Drop the old ``String(100)`` columns.

Downgrade reverses the process: re-add the string columns, reverse-join
from the FK columns to ``users.username``, drop the FK constraints,
drop the FK columns, delete the placeholder user. Round-trip is tested
in ``backend/tests/test_audit_actor_fk.py``.

This migration is written by hand (not autogenerated) because
``alembic/env.py`` only imports a subset of the project's models and
``--autogenerate`` would emit spurious DROP operations against the
tables it cannot see.
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ddc07dd9e1c"
down_revision: Union[str, Sequence[str], None] = "dfc94a9994c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Structurally-valid bcrypt-like placeholder hash. Not a real password —
# ``is_active=False`` prevents login even if someone tried to use it.
_PLACEHOLDER_HASH = "$2b$12$placeholderplaceholderplaceholderplaceholderplaceholderpl"


def upgrade() -> None:
    """FK-ify the four audit-actor columns with data-preserving JOINs."""
    bind = op.get_bind()

    # -----------------------------------------------------------------
    # 1. Seed the _system_migration_ placeholder user.
    # -----------------------------------------------------------------
    # ON CONFLICT keeps the migration idempotent if the row already
    # exists (e.g. re-running after a partial failure).
    op.execute(
        sa.text(
            """
            INSERT INTO users (
                email, username, hashed_password, full_name, role,
                is_active, is_verified, is_fixture_user,
                failed_login_attempts, created_at
            )
            VALUES (
                'system-migration@hnf1b-db.local',
                '_system_migration_',
                :hash,
                'System Migration Placeholder',
                'viewer',
                FALSE,
                FALSE,
                FALSE,
                0,
                NOW()
            )
            ON CONFLICT (username) DO NOTHING
            """
        ).bindparams(hash=_PLACEHOLDER_HASH)
    )

    # Resolve the placeholder id once so the data-migration UPDATEs
    # below can use it as a literal parameter.
    placeholder_id = bind.execute(
        sa.text("SELECT id FROM users WHERE username = '_system_migration_'")
    ).scalar()
    assert placeholder_id is not None, (
        "failed to seed _system_migration_ placeholder user"
    )

    # -----------------------------------------------------------------
    # 2. Add the four new nullable BIGINT columns.
    # -----------------------------------------------------------------
    op.add_column(
        "phenopackets",
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "phenopackets",
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "phenopackets",
        sa.Column("deleted_by_id", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "phenopacket_audit",
        sa.Column("changed_by_id", sa.BigInteger(), nullable=True),
    )

    # -----------------------------------------------------------------
    # 3. Populate the FK columns via JOIN on users.username.
    # -----------------------------------------------------------------
    op.execute(
        sa.text(
            """
            UPDATE phenopackets p
            SET created_by_id = u.id
            FROM users u
            WHERE u.username = p.created_by
              AND p.created_by IS NOT NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE phenopackets p
            SET updated_by_id = u.id
            FROM users u
            WHERE u.username = p.updated_by
              AND p.updated_by IS NOT NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE phenopackets p
            SET deleted_by_id = u.id
            FROM users u
            WHERE u.username = p.deleted_by
              AND p.deleted_by IS NOT NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE phenopacket_audit a
            SET changed_by_id = u.id
            FROM users u
            WHERE u.username = a.changed_by
              AND a.changed_by IS NOT NULL
            """
        )
    )

    # -----------------------------------------------------------------
    # 4. Fall back unmapped non-null strings to the placeholder id.
    # -----------------------------------------------------------------
    # Rows whose ``*_by`` string didn't match any users.username (e.g.
    # legacy "hnf1b-db v1.0.0" importer tag) become the placeholder so
    # the later NOT NULL FK check on the string doesn't leak into the
    # FK side.
    op.execute(
        sa.text(
            "UPDATE phenopackets SET created_by_id = :pid "
            "WHERE created_by IS NOT NULL AND created_by_id IS NULL"
        ).bindparams(pid=placeholder_id)
    )
    op.execute(
        sa.text(
            "UPDATE phenopackets SET updated_by_id = :pid "
            "WHERE updated_by IS NOT NULL AND updated_by_id IS NULL"
        ).bindparams(pid=placeholder_id)
    )
    op.execute(
        sa.text(
            "UPDATE phenopackets SET deleted_by_id = :pid "
            "WHERE deleted_by IS NOT NULL AND deleted_by_id IS NULL"
        ).bindparams(pid=placeholder_id)
    )
    op.execute(
        sa.text(
            "UPDATE phenopacket_audit SET changed_by_id = :pid "
            "WHERE changed_by IS NOT NULL AND changed_by_id IS NULL"
        ).bindparams(pid=placeholder_id)
    )

    # -----------------------------------------------------------------
    # 5. Add FK constraints with ON DELETE SET NULL.
    # -----------------------------------------------------------------
    op.create_foreign_key(
        "fk_phenopackets_created_by_id_users",
        "phenopackets",
        "users",
        ["created_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_phenopackets_updated_by_id_users",
        "phenopackets",
        "users",
        ["updated_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_phenopackets_deleted_by_id_users",
        "phenopackets",
        "users",
        ["deleted_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_phenopacket_audit_changed_by_id_users",
        "phenopacket_audit",
        "users",
        ["changed_by_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # -----------------------------------------------------------------
    # 6. Index the one FK we query by (created_by_id). The others are
    # rarely filtered on so we skip them per plan line 736.
    # -----------------------------------------------------------------
    op.create_index(
        "ix_phenopackets_created_by_id",
        "phenopackets",
        ["created_by_id"],
        unique=False,
    )

    # -----------------------------------------------------------------
    # 7. Drop the old String(100) columns.
    # -----------------------------------------------------------------
    op.drop_column("phenopackets", "created_by")
    op.drop_column("phenopackets", "updated_by")
    op.drop_column("phenopackets", "deleted_by")
    op.drop_column("phenopacket_audit", "changed_by")


def downgrade() -> None:
    """Reverse the FK-ify migration.

    Re-add the ``String(100)`` columns, reverse-join from the FK ids
    back to ``users.username``, drop the FK constraints + columns,
    then delete the placeholder user.
    """
    # -----------------------------------------------------------------
    # 1. Re-add the original String(100) columns (nullable).
    # -----------------------------------------------------------------
    op.add_column(
        "phenopackets",
        sa.Column("created_by", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "phenopackets",
        sa.Column("updated_by", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "phenopackets",
        sa.Column(
            "deleted_by",
            sa.String(length=100),
            nullable=True,
            comment="Username who performed the soft delete",
        ),
    )
    op.add_column(
        "phenopacket_audit",
        sa.Column("changed_by", sa.String(length=100), nullable=True),
    )

    # -----------------------------------------------------------------
    # 2. Reverse-join to repopulate the string columns.
    # -----------------------------------------------------------------
    op.execute(
        sa.text(
            """
            UPDATE phenopackets p
            SET created_by = u.username
            FROM users u
            WHERE u.id = p.created_by_id
              AND p.created_by_id IS NOT NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE phenopackets p
            SET updated_by = u.username
            FROM users u
            WHERE u.id = p.updated_by_id
              AND p.updated_by_id IS NOT NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE phenopackets p
            SET deleted_by = u.username
            FROM users u
            WHERE u.id = p.deleted_by_id
              AND p.deleted_by_id IS NOT NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE phenopacket_audit a
            SET changed_by = u.username
            FROM users u
            WHERE u.id = a.changed_by_id
              AND a.changed_by_id IS NOT NULL
            """
        )
    )

    # -----------------------------------------------------------------
    # 3. Drop the index, FK constraints and the FK id columns.
    # -----------------------------------------------------------------
    op.drop_index("ix_phenopackets_created_by_id", table_name="phenopackets")
    op.drop_constraint(
        "fk_phenopacket_audit_changed_by_id_users",
        "phenopacket_audit",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_phenopackets_deleted_by_id_users",
        "phenopackets",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_phenopackets_updated_by_id_users",
        "phenopackets",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_phenopackets_created_by_id_users",
        "phenopackets",
        type_="foreignkey",
    )
    op.drop_column("phenopacket_audit", "changed_by_id")
    op.drop_column("phenopackets", "deleted_by_id")
    op.drop_column("phenopackets", "updated_by_id")
    op.drop_column("phenopackets", "created_by_id")

    # -----------------------------------------------------------------
    # 4. Delete the placeholder user. No rows can still FK at it
    # because we just dropped every column that did.
    # -----------------------------------------------------------------
    op.execute(sa.text("DELETE FROM users WHERE username = '_system_migration_'"))
