default:
  hnf1b_db_local:
    dbtype: mysql
    dbname: hnf1b_db
    user: bernt
    password: "HNF1B-db"
    server: "0.0.0.0"
    host: "127.0.0.1"
    port: "6612"
    port_self: "7779"
    secret: <Dt'-XxOKzi6&]|BWyAx(g,DR:!M:etI`n(+^v]DKP!hm#IEI}`'#3NH7(:2
    refresh: 360
  hnf1b_db:
    dbtype: mysql
    dbname: hnf1b_db
    user: bernt
    password: "HNF1B-db"
    server: "0.0.0.0"
    host: "hnf1b_mysql"
    port: "3306"
    port_self: "6668"
    secret: <Dt'-XxOKzi6&]|BWyAx(g,DR:!M:etI`n(+^v]DKP!hm#IEI}`'#3NH7(:2
    refresh: 3600
