default:
  hnf1b_db_local:
    dbtype: mysql
    dbname: hnf1b_db
    user: bernt
    password: "HNF1B-db"
    server: "0.0.0.0"
    host: "hnf1b_mysql"
    port: "3306"
    port_self: "6612"
    secret: mHzU/}bny4-==rm0]9~bsq.2Ob2`lHgu2#+K(/Dih#7bN@KmMLf\AK9y:Inf+FN
    refresh: 3600
